# Generated by hand to migrate proofs from session-based linkage to task-based linkage.
from django.db import migrations, models
import django.db.models.deletion


def copy_session_task(apps, schema_editor):
    Proof = apps.get_model("proofs", "Proof")
    for proof in Proof.objects.select_related("session").all().iterator():
        if proof.task_id:
            continue
        proof.task_id = proof.session.task_id
        proof.save(update_fields=["task"])


class Migration(migrations.Migration):

    dependencies = [
        ("proofs", "0001_initial"),
        ("core", "0004_taskcomment"),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proof",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proofs",
                to="core.task",
            ),
        ),
        migrations.RunPython(copy_session_task, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="proof",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proofs",
                to="core.task",
            ),
        ),
        migrations.RemoveField(
            model_name="proof",
            name="session",
        ),
    ]
