# Generated by Django 4.2.27 on 2026-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_learningpath_portfolioproject_portfolioasset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="difficulty_level",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("locked", "Locked"),
                    ("completed", "Completed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_size",
            field=models.CharField(default="medium", max_length=20),
        ),
        migrations.AddField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[("standard", "Standard"), ("remedial", "Remedial")],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="xp_reward",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="task",
            name="youtube_link_ar",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="youtube_link_en",
            field=models.URLField(blank=True),
        ),
    ]
