# Generated by hand to cache LinkedIn-ready portfolio text on objectives.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_taskcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="objective",
            name="linkedin_generated_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
