# Generated by Django 4.2.27 on 2026-02-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="current_status",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
