# Generated by Django 4.2.27 on 2026-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_is_trainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="highest_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="total_xp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
