# Generated by Django 4.2.27 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_notification_type_paymentrecord_chatthread_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertprofile",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="availability_schedule",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="expertise_level",
            field=models.CharField(default="junior", max_length=20),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="is_accepting_new_students",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="max_students",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="subscription_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="wallet_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="expertassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("awaiting_payment", "Awaiting Payment"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
