# Generated by Django 4.2.27 on 2026-05-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_expertrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertprofile",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
