# Generated by Django 4.2.27 on 2026-02-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("interview", "Interview"),
                            ("tagging", "Tagging"),
                            ("time_estimation", "Time Estimation"),
                            ("scheduling", "Scheduling"),
                            ("proof_analysis", "Proof Analysis"),
                            ("challenge_generation", "Challenge Generation"),
                        ],
                        default="all",
                        max_length=32,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("openai", "OpenAI"),
                            ("mock", "Mock"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("weight_path", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("capability", "name"),
                "unique_together": {("name", "capability")},
            },
        ),
    ]
